config/routes.rb
NueDrop::Application.routes.draw do
  get "pages/index"
  devise_for :users

  root :to => "pages#index"
  resources :pages do
     post 'connect' => "pages#connect"
  end

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def after_sign_in_path_for(resource)
    page_path(current_user)
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
 require 'dropbox_sdk'
     
  def index
    
  end
  def show
    
    
       flow = DropboxOAuth2FlowNoRedirect.new('s47og90n7ip99ox', '6u8vs2x2sw10e9i')  
    @authorize_url = flow.start()
   
    end
    
  def connect
    if params[:code]
        flow = DropboxOAuth2FlowNoRedirect.new('s47og90n7ip99ox', '6u8vs2x2sw10e9i')
    code = params[:code]
    access_token, user_id = flow.finish(code)
    client = DropboxClient.new(access_token)    
    root_metadata = client.metadata('/website/')
    
    root_metadata['contents'].each do |meta|
      @file = meta['path']
    end
    contents = client.get_file(@file)
    copyfile @file,contents
    end
  end
  def copyfile file,contents
    
    file.slice! '/website'
    username = current_user.email.split('@').first
   
    Dir.mkdir("public\/#{username}") unless File.exists?("public\/#{username}")
     @your_page = "#{username}#{file}"
    open("public\/#{username}#{file}", 'wb') do  |f| 
      f <<  contents 
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NueDrop</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/connect.html.erb
<h1>
	Your page loded successfully please <a href="/<%= @your_page;  %>">click here</a> view
	
</h1>

app/views/pages/index.html.erb
<body>

<div class="header-100-perc">
<div class="header">
<h1> NueDrops </h1>
<div class="login">
    <div class="row" style="width: 470px;">
		<div class="col-md-4 col-md-offset-4" style="width: 91%;margin-left: 0;">
    		<div class="panel panel-default">
			  	
			  	<div class="panel-body">
			    	<%= form_for(User.new, :url => session_path(User.new)) do |f| %>
                    <fieldset>
			    	  	<div class="form-group">
			    		     <%= f.email_field :email, :autofocus => true,:class => 'form-control',:placeholder=>"Email" %>
			    		</div>
			    		<div class="form-group">
			    			<%= f.password_field :password ,:class => 'form-control' ,:placeholder=>"Password" %>
			    		</div>
			    		<div class="checkbox">
			    	    	<label>
			    	    		<input name="remember" type="checkbox" value="Remember Me"> Remember Me
			    	    	</label>
			    	    </div>
			    	    </div>
			    		<%= f.submit "Sign in" ,:class=>'btn btn-lg btn-success btn-block' %>
			    		<% end %>
			    	</fieldset>
			      	</form>
			    </div>
			</div>
		</div>
	</div>

</div>
</div>
</div>

<div class="wrapper">
<div class="content">
<div class="drop-images"><img src="assets/drop.png" width="450" height="219" /></div>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-4 well well-sm">
      <legend style="margin-bottom: 10px;"><a href="http://www.jquery2dotnet.com"><i class="glyphicon glyphicon-globe"></i></a> Sign up!</legend>
     
      	<%= form_for(User.new, :url => registration_path(User.new)) do |f| %>
        
        <%= f.email_field :email, :autofocus => true, :class => 'form-control',:placeholder => 'Email' %>
          <%= f.password_field :password ,:class => 'form-control',:placeholder => 'Password'  %>
            <%= f.password_field :password_confirmation,:class => 'form-control' ,:placeholder => 'Password' %>
       
        <br>
        <%= f.submit "Sign up" ,:class=>"btn btn-lg btn-primary btn-block" %>
        
        <% end %>
        
      </form>
    </div>
  </div>
</div>
</div>
</div>
<div class="footer-100-per">
<div class="footer">
<p>Copyright © 2013 NueDrops</p>
<p style="float:right;">Designed by <a href="https://www.facebook.com/nahaz.meawo?ref=tn_tnmn" target="_blank">NaHaZ Meawo</a></p>
</div>
</div>

</body>
</html>

app/views/pages/show.html.erb
<link href='http://fonts.googleapis.com/css?family=Rationale' rel='stylesheet' type='text/css'>
<div class="header-100-perc">
<div class="header">
<h1> NueDrops </h1>
<%= link_to('Logout', destroy_user_session_path, :method => :delete, :class => 'logout') %>      
 </div>
</div>

<div class="wrapper">
<div class="" align="center" style="margin-top:10px;">
	
		<div class="connect-drop-base">
			<img src="/assets/dropbox-logo-large.png" width="1000" height="339" />
			
		<%= link_to '', @authorize_url ,:target=>"_new",:class=>'conect-btn' %>
		<%= form_tag(page_connect_path(current_user)) do %>
		<br>
			
		<div style="width:50% margin:auto;" >
		<input type="text" class="form-control" name="code" placeholder="Return Code">
		<input type="submit" value="Submit Code" class="btn btn-lg btn-success btn-block" />
		</div>
		<% end -%>
			</div>
</div>
</div>
<!-- <div class="footer-100-per">
<div class="footer">
<p>Copyright © 2013 NueDrops</p>
<p style="float:right;">Designed by <a href="https://www.facebook.com/nahaz.meawo?ref=tn_tnmn" target="_blank">NaHaZ Meawo</a></p>
</div>
</div> -->